using CK.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CK.Cris
{
    /// <summary>
    /// An executing command carries the <see cref="Payload"/>, the <see cref="ValidationResult"/> and the eventual <see cref="RequestCompletion"/>.
    /// of a <see cref="ICommand"/> or <see cref="ICommand{TResult}"/>.
    /// <para>
    /// This is the non generic interface of <see cref="IOutgoingCommand{T}"/>.
    /// </para>
    /// </summary>
    public interface IExecutingCommand
    {
        /// <summary>
        /// Gets the <see cref="ICommand"/> or <see cref="ICommand{TResult}"/>.
        /// </summary>
        IAbstractCommand Payload { get; }

        /// <summary>
        /// Gets a token that identifies the initialization of the command execution.
        /// </summary>
        ActivityMonitor.Token IssuerToken { get; }

        /// <summary>
        /// Gets the UTC date and time creation of this executing command.
        /// </summary>
        DateTime CreationDate { get; }

        /// <summary>
        /// Gets the validation result of the executing command.
        /// When this <see cref="CrisValidationResult.Success"/> is false,
        /// the <see cref="Completion"/> contains a <see cref="ICrisResultError"/> with the <see cref="CrisValidationResult.Errors"/>
        /// lines. 
        /// </summary>
        Task<CrisValidationResult> ValidationResult { get; }

        /// <summary>
        /// Gets a task that is completed when the execution is terminated.
        /// The task's value can be:
        /// <list type="bullet">
        ///  <item>A <see cref="ICrisResultError"/> on validation or execution error.</item>
        ///  <item>A successful null result on success when <see cref="Payload"/> is a <see cref="ICommand"/>.</item>
        ///  <item>A successful result object if Payload is a <see cref="ICommand{TResult}"/>.</item>
        /// </list>
        /// </summary>
        Task<object?> RequestCompletion { get; }

        /// <summary>
        /// Gets the events that have been generated by the command execution.
        /// </summary>
        ICollector<IExecutingCommand, IEvent> Events { get; }

    }
}
