<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CK.Cris</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Cris" Version="0.43.1--ci.1" />
    <PackageReference Include="CK.PerfectEvent" Version="27.0.1--ci.1" />
  </ItemGroup>
</Project>