<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Cris" Version="0.43.2" />
    <PackageReference Include="CK.CodeGen" Version="15.0.2" />
    <PackageReference Include="CK.StObj.Runtime" Version="33.0.2" />
  </ItemGroup>
</Project>